# Generated by Django 5.1.7 on 2025-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('ingredients', models.TextField(max_length=250)),
                ('instructions', models.TextField(max_length=250)),
            ],
        ),
    ]
